### ISSUE TITLE
Authz vote not working for an authz granted vote permission

### ISSUE THREAD

**Issue by andynog** [informalsystems/multisig#24]
This is not in particular directly related to multisig but I will open an issue since this might be related to the authz support in multisig.

A vote authz permission (`/cosmos.gov.v1beta1.MsgVote`) was granted from the multisig CEC-I account to Josh's key.

Josh tried to vote on a CosmosHub proposal using this key but it's not working. When executing the `gaiad tx authz exec` command he gets an error message. Not sure what is causing that so keeping this issue open for tracking.

### Steps to reproduce

Generated a tx for the gov proposal vote:

```
gaiad tx gov vote 69 no --from <CEC-I cosmos multisig address> --fees 3000uatom --chain-id cosmoshub-4 --generate-only > tx.json
```

Then when executing that tx using authz he gets an error

```
gaiad tx authz exec tx.json --from <CEC-I cosmos josh address> 
```

Error:

```
Error: error parsing public key: invalid magic in compressed pubkey string: 0
Usage:
  gaiad tx authz exec [msg_tx_json_file] --from [grantee] [flags]
```

### Notes

- He was able to successfully submit a `tx bank send` transaction sending some tokens back to the account that funded his account
- He tried the `tx authz exec` many times (before and after the tx send) to ensure that his account existed on chain
- We also tried the `gaiad tx authz exec` passing the `--ledger` flag. But he doesn't even get a prompt in his Ledger, it errors out before that. 
- Checking the grant for his account it seems fine 

```
gaiad query authz grants <josh cosmos> <cosmos multisig>


grants:
- authorization:
    '@type': /cosmos.authz.v1beta1.GenericAuthorization
    msg: /cosmos.gov.v1beta1.MsgVote
  expiration: "2023-05-03T17:57:46Z"
pagination:
  next_key: null
  total: "0"

```

### Things to test

- Maybe we will need someone else that has 'vote' granted via authz to their individual account to test this in order to eliminate the possibility that this issue is caused by a configuration of his key on his machine. If someone else can successfully submit the tx then it might be a configuration issue.
